//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BakerySquared.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public string Name { get; set; }
        public string Title { get; set; }
        public string Desk { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Id { get; set; }
        public string Manager { get; set; }
    }
}
